title: Ervas e Temperos
email: email@email.com
description: >- # this means to ignore newlines until "baseurl:"
  Aqui você encontrará informações sobre diversas ervas e temperos!
baseurl: "/herbs-and-spices" # the subpath of your site, e.g. /blog
url: "https://jsilvaigor.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:slug

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr"
footer_text: "Theme by rhl-bthr"

favicon_location: assets/favicon.ico

sass:
  style: compressed
  sass_dir: css
  verbose: true

navbar:
  - name: "Sobre"
    link: "about"
  - name: "PDF"
    absolute-link: "#"

exclude:
  - create_posts.js
  - Gemfile
  - Gemfile.lock
  - Readme.md
