baseURL = 'https://jsilvaigor.github.io/'
languageCode = 'pt-br'
title = 'Herbs And Spices'
theme = 'anubis2'
canonifyURLs = true
[permalinks]
[permalinks.page]
posts = '/:slug'

[params]
style = 'dark-without-switcher'
